sudo: false # use container based infrastructure

language: node_js

node_js:
  - 0.12

before_install:
  - npm install -g cordova ionic gulp

script:
  - gulp install
  - gulp test

env:
  global:
    # encrypted COVERITY_SCAN_TOKEN
    - secure: "gpz5PiiqoMb+ga30Ovm2KT3OxRWdgaCrKV4Tmxgwg96hyTIm7a2boZvmMTPGJIbhQso9+cdV6QUMRym73pDMXX+o0HDugkFSY3yigd4aVv1X28KhIiE9eWvPxz2ltGl9od2n7XUnHgFwJZ6hhvL1ab9piYbPrFpiADeANXFqGP4="

addons:
  coverity_scan:
    project:
      name: Grisu-NOE/mobile-app
      version: 1.1.0
      description: Build submitted by Travis CI
    notification_email: office@alex-gassner.at
    build_command_prepend: ""
    build_command: gulp install
    branch_pattern: master